### ISSUE TITLE
Quellen generell und Einzelquellen

### ISSUE THREAD

**Issue by Irmlind** [Detmolder-Hoftheater/TheatreTool_1-Dev#28]
Bei den Aufführungsdaten sollte nicht "Uraufführungen" stehen, sondern eben "Aufführungsdaten". Die Spalten sind auch sehr breit.

**Comment by KristinaRichts** [comment]
s. issue #24

**Comment by elena1113** [comment]
Fix for Quellen generell und Einzelquellen #28 and #24
