### ISSUE TITLE
Faksimiles

### ISSUE THREAD

**Issue by Irmlind** [Detmolder-Hoftheater/TheatreTool_1-Dev#29]
Könnte man die Faksimiles bei den tiefenerschlossenen Werken in der gleichen Reihenfolge anzeigen wie die Quellen aufgenommen sind?
Bisher fehlen hier die Textquellen. Müssen diese durch edirom laufen, um sie einzubinden? Ich habe schon einmal erste Textquellen dort ebenfalls "vertaktet", aber noch nicht alle.

**Comment by elena1113** [comment]
Ich werde diesen Bug auf zwei Unterschiedliche teile, wenn es ok ist;-()

Sources: sort facsimiles in tree #21 
Source: Show Textsources for Extended Works #30

und Faksimiles #29 dann schliessen.
