### ISSUE TITLE
Anzeige?

### ISSUE THREAD

**Issue by Irmlind** [Detmolder-Hoftheater/TheatreTool_1-Dev#34]
Zu dem Stück "Sieben Mädchen in Uniform" werden die Quellen nicht angezeigt. H220093.

Woran kann das liegen?

**Comment by elena1113** [comment]
In Source:
<relation rel="isEmbodimentOf" target="H020055_expr1"/>, statt "H020055.xml_expr1"
--------------------------------
In Werk fehlt noch:
<relationList>
		<relation rel="hasRealization" target="#H020053_expr1"/>
</relationList>
-------------------------------
In Source gibt es noch:
<identifier analog="marc:040a">DE-633</identifier>
es wird momentan von dem Tool nicht unterstützt?
Wenn man dies braucht, bitte ein Bug öffnen, um das Tool zu erweitern.

In DB sind die Daten geändert, bitte, noch für SVN die Daten ändern.

**Comment by elena1113** [comment]
Es ist irgendwas mit der Formatierung falsch gelaufen:-(

In Source Zeile 2288: target="H020055_expr1", statt target="H020055.xml_expr1"
Und in dem Werk fehlt noch Relation zu der Expression-Datei

**Comment by Irmlind** [comment]
<identifier authURI="https://opac.rism.info" authority="RISM" analog="marc:040a">DE-633</identifier>

brauchen wir diese Zeile? @KristinaRichts

**Comment by Irmlind** [comment]
Ist angegeben als RSIM identifier, habe ich jetzt auskommentiert. @KristinaRichts

**Comment by KristinaRichts** [comment]
Nein, die Zeile benötigen wir nicht. Ist wohl versehentlich stehen geblieben.

**Comment by Irmlind** [comment]
Gut, dann lösche ich sie. DAnke Irmlind
