### ISSUE TITLE
ANzeige bei Mus-n 107 "Die Waldmänner"

### ISSUE THREAD

**Issue by Irmlind** [Detmolder-Hoftheater/TheatreTool_1-Dev#36]
Der 2. Band der Partitur wird in den Quellen nicht angezeigt, ich finde aber keinen Fehler im XML.

**Comment by elena1113** [comment]
In H220062.xml, Zeile 1730 steht target="#H220062_score1", sollte aber target="#H220062_score2" sein. Deswegen wird es nicht angezeigt. Die Daten in DN habe ich geändert, bitte, auch in SVN ändern!
