### ISSUE TITLE
Rollenverlinkungen in Personendatensätzen

### ISSUE THREAD

**Issue by KristinaRichts** [Detmolder-Hoftheater/TheatreTool_1-Dev#61]
Bei den Rollenverlinkungen in den Personendatensätzen fehlen häufig Leerzeichen, z.B. zwischen Rollenname und Rollenbeschreibung (Beispieldatensatz Frl. Herwegh, H000775)

**Comment by elena1113** [comment]
commit 2ca5872a78b74e793b44cb817a80b0388bd1abec
