### ISSUE TITLE
H001014

### ISSUE THREAD

**Issue by Irmlind** [Detmolder-Hoftheater/TheatreTool_1-Dev#69]
Die Person unter H001014 wird unter Müller im Portal angezeigt, heißt aber mit Familiennamen "Heinz".

**Comment by elena1113** [comment]
Die Personen:

H001017
H001019
H001020
H001014

haben id „H001014“. Deswegen werden falsche Daten angezeigt.
Fixed in XML

**Comment by Irmlind** [comment]
Oh, da habe ich wohl zu viel kopiert. Korrigiere ich sofort.

Herzliche Grüße
Irmlind

P.S. Ich denke, Du bist noch krank ...

**Comment by elena1113** [comment]
Ja, bin ich noch,
es ist aber echt langweilig den ganzen Tag im Bett zu liegen und wenn die Medikamente wirken, man denkt, dass man wieder gesund ist.., ich habe die Erkältung schon seit Sonntag.

Schöne Grüße,
Elena
